name: Release

# When tag 'v*.*.*' is pushed, run this job.
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm audit --production
      - run: npm run lint
      - run: npm test

      - run: npm run electron:build -- --arm64 --mac --dir
      - run: npm run electron:build -- --x64 --mac --dir

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: true

      - name: Zip Release Asset for x64
        run: |
          cd dist_electron/mac/
          zip -r PomodoroTimer.app.x64.zip PomodoroTimer.app

      - name: Zip Release Asset for arm64
        run: |
          cd dist_electron/mac-arm64/
          zip -r PomodoroTimer.app.arm64.zip PomodoroTimer.app

      - name: Upload Release Asset for x64
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist_electron/mac/PomodoroTimer.app.x64.zip
          asset_name: PomodoroTimer.app.x64.zip
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for arm64
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist_electron/mac-arm64/PomodoroTimer.app.arm64.zip
          asset_name: PomodoroTimer.app.arm64.zip
          asset_content_type: application/octet-stream
